// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"DarkPlasma_ChoiceExtension","status":true,"description":"選択肢を拡張する","parameters":{"maxPageRows":"6"}},
{"name":"DarkPlasma_ChoiceHelp","status":false,"description":"選択肢にヘルプを表示する","parameters":{}},
{"name":"TorigoyaMZ_CommonMenu","status":true,"description":"メニューからコモンイベント呼び出しプラグイン (v.1.0.0)","parameters":{"base":"","baseItems":"[\"{\\\"name\\\":\\\"テレポート\\\",\\\"commonEvent\\\":\\\"1\\\",\\\"switchId\\\":\\\"0\\\",\\\"visibility\\\":\\\"true\\\",\\\"note\\\":\\\"\\\"}\"]"}}
];
